services:
  zipkin-server:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    restart: always
    networks:
      - gustavo-network

  naming-server:
    image: gustavosilvalgs/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    restart: always
    depends_on:
      - zipkin-server
    networks:
      - gustavo-network

  api-gateway:
    image: gustavosilvalgs/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    restart: always
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
    depends_on:
      - zipkin-server
      - naming-server
    networks:
      - gustavo-network

  book-db:
    image: mysql:9.3.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
    ports:
      - 3310:3306 # 3310 no host -> 3306 no container
    networks:
      - gustavo-network


  exchange-db:
    image: mysql:9.3.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: exchange_service
    ports:
      - 3308:3306 # 3310 no host -> 3306 no container
    networks:
      - gustavo-network

  exchange-service:
    image: gustavosilvalgs/exchange-service
    restart: always
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://exchange-db:3306/exchange_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - zipkin-server
      - naming-server
      - exchange-db
    ports:
      - 8000:8000
    networks:
      - gustavo-network

  book-service:
    image: gustavosilvalgs/book-service
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3306/book_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - zipkin-server
      - naming-server
      - book-db
    ports:
      - 8100:8100
    networks:
      - gustavo-network

networks:
  gustavo-network:
    name: gustavo-network
    driver: bridge

#    gustavosilvalgs/api-gateway:0.0.1-SNAPSHOT